name: Renovate

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: renovatebot/github-action@v46.2.4
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_HOST_RULES: |
            [{"matchHost":"ghcr.io","hostType":"docker","username":"x-access-token","password":"${{ secrets.GHCR_TOKEN }}"}]